extends:
  - ["spectral:oas", "off"]
rules:
  api-must-have-description:
    message: "API info must have a description"
    given: "$.info"
    severity: error
    then:
      field: description
      function: truthy
  api-must-have-contact:
    message: "API info must have contact"
    given: "$.info"
    severity: warn
    then:
      field: contact
      function: defined
  operations-must-have-security:
    message: "Operations must define security"
    given: "$.paths[*][get,post,put,delete,patch]"
    severity: error
    then:
      field: security
      function: defined
